version: '2'
output: 'prefixed'

tasks:
  bin:
    desc: Build binary
    cmds: 
      - cargo build --release --target x86_64-unknown-linux-musl
  bin-cov:
    desc: Build coverage binary
    cmds: 
      - cargo build
    env:
      RUSTFLAGS: "-C instrument-coverage" 
      LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
  format:
    desc: Format code via rustfmt
    cmds: 
      - rustfmt --check src/main.rs
      - rustfmt --check tests/test.rs
  format-fix:
    desc: Fix format code via rustfmt
    cmds: 
      - rustfmt src/main.rs
      - rustfmt tests/test.rs
  lint:
    desc: Run linter clippy
    deps:
      - format
    cmds: 
      - cargo clippy --color=always -- -Dwarnings
  changelog:
    desc: Add new changelog entry
    cmds:
      - ish: changelogger
  test:
    desc: Run tests
    cmds:
      - cargo test --color=always
    env:
      RUSTFLAGS: "-C instrument-coverage" 
      LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
  cov:
    desc: Generate coverage report
    cmds:
      - mkdir -p coverage
      - rust-profdata merge -sparse *.profraw -o coverage/blogstage.profdata
      - rust-cov show target/debug/blogstage -instr-profile=coverage/blogstage.profdata --ignore-filename-regex=/.cargo --format=html --show-line-counts-or-regions > coverage/index.html
