version: '2'
output: 'prefixed'

tasks:
  bin-cov:
    cmds:
      - cargo build
    env:
      RUSTFLAGS: "-C instrument-coverage" 
      LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
  test:
    cmds:
      - cargo test --color=always
    env:
      RUSTFLAGS: "-C instrument-coverage" 
      LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
  cov:
    cmds:
      - mkdir -p coverage
      - rust-profdata merge -sparse *.profraw -o coverage/blogstage.profdata
      - rust-cov show target/debug/blogstage -instr-profile=coverage/blogstage.profdata --ignore-filename-regex=/.cargo --format=html --show-line-counts-or-regions > coverage/index.html
