
on: [push]
name: Blogstage
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Task
        run: curl -Ls https://git.io/ttask.sh | sh
      - name: Run lint
        run: ./bin/task lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install coverage profiler
        run: cargo install cargo-binutils
      - name: Install Task
        run: curl -Ls https://git.io/ttask.sh | sh
      - name: Run tests
        run: ./bin/task test
      - name: Generate coverage report
        if: always()
        run: ./bin/task cov
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
  build:
    name: Build blogstage
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: install task
        run: curl -Ls https://git.io/ttask.sh | sh
      - run: ./bin/task bin
      - run: mv ci-build/blogstage ci-build/blogstage_${{ matrix.goos }}_${{ matrix.goarch }}
      - uses: actions/upload-artifact@master
        with:
          name: build-artifacts
          path: ci-build
  release:
    name: Release blogstage
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: install changelogger
        run: curl -Ls https://git.io/changelogger.sh | sh
      - uses: actions/download-artifact@master
        with:
          name: build-artifacts
          path: ci-build
      - name: Save changelog entries of current release
        run: ./bin/changelogger release last > CHANGELOG_RELEASE.md
      - name: Print changelog entries for debugging
        run: cat CHANGELOG_RELEASE.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ci-build/*
          body_path: CHANGELOG_RELEASE.md
          token: ${{ secrets.GITHUB_TOKEN }}
